version: '3'
services:
  db:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: checkitDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d