version: '3'
services:
  db:
    build: .
    ports:
      - "9010:9010"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./createtable:/docker-entrypoint-initdb.d

volumes:
  db_data:
  